#!/bin/sh

uname_s=`uname -s`
oskind=
needcython=
needsetuptools=

if test "$uname_s" = "Linux"
then
    if test -f /etc/lsb-release
    then
        . /etc/lsb-release
        if test -n "$DISTRIB_RELEASE"
        then
            osrel=$DISTRIB_RELEASE
        else
            echo "Could not find osrel in /etc/lsb-release"
            exit 1
        fi
        oskind=ubuntu
    elif test -f /etc/redhat-release
    then
        osrel="`cat /etc/redhat-release | sed -e 's/CentOS release *//' -e 's/ *(Final)//'`"
        oskind=redhat
    fi

elif test "$uname_s" = "FreeBSD"
then
    osrel="`uname -r`"
    oskind=freebsd
else
    echo "OS not supported: $uname_s"
    exit 1
fi

# check cython setuptools

if ! which cython >/dev/null 2>&1
then
    needcython=1
else
    v="`cython -V 2>&1`"
    #v=`echo $v`
    if test "$v" != "Cython version 0.19.1"
    then
        echo "Cython version is not what is required: $v"
        exit 1
    fi
fi

if ! python -c 'import setuptools' >/dev/null 2>&1
then
    needsetuptools=1
fi

echo osrel $osrel oskind $oskind needcython $needcython needsetuptools $needsetuptools

if test $oskind = ubuntu
then
    MAKEFILE=`dirname $0`/Makefile.deb

fi

if ! test -e $WORKSPACE/bin/activate
then
    virtualenv $WORKSPACE
fi

if ! test -e $WORKSPACE/bin/make-deb
then
    cp `dirname $0`/bin/make-deb $WORKSPACE/bin/
fi

export BUILDROOT=$WORKSPACE
export PREFIX=$WORKSPACE
export EQ_DEV_CYTHONVER=0.19.1

make -f $MAKEFILE shrapnel
